/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CriarObjeto.java
 *
 * Created on 12/09/2011, 23:39:28
 */
package visao;

import controle.ControlaTudo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Aresta;
import modelo.Face;
import modelo.Objeto;
import modelo.Vertice;

/**
 *
 * @author TyTu
 */
public class CriarObjeto extends javax.swing.JFrame {

    /** Creates new form CriarObjeto */
    public CriarObjeto() {
        initComponents();
    }
    private List<Vertice> pontos = new ArrayList<Vertice>();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerando o objeto");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jButton1.setText("Rotação");
        jButton1.setAutoscrolls(true);

        jButton2.setText("Extrusão");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        if (!pontos.isEmpty()) {
            jPanel1.getGraphics().drawLine((int) pontos.get(pontos.size() - 1).getX(), (int) pontos.get(pontos.size() - 1).getY(), evt.getX(), evt.getY());
        }
        System.out.println("Criar Objeto - ADD Ponto");
        pontos.add(new Vertice(evt.getX(), evt.getY(), 0));

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (pontos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não tem pontos!");
        } else {


            int z;
            for (;;) {
                try {
                    z = Integer.parseInt(JOptionPane.showInputDialog("Variação em Z"));
                    System.out.println("Criar Objeto - Variação em Z= "+z);
                    break;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Valor digitado incorreto!");
                    e.printStackTrace();
                }
            }
            Objeto o = new Objeto();
            Face f1 = new Face();
            Face f2 = new Face();

            for (int i = 1; i < pontos.size(); i++) { //Cria uma face com o desenho
                Aresta a = new Aresta();
                a.setV1(new Vertice(pontos.get(i - 1)));
                a.setV2(new Vertice(pontos.get(i)));
                
                //face lateral
                    Face f3= new Face();
                    Aresta b = new Aresta();                    
                    b.setV1(new Vertice(pontos.get(i)));
                    b.setV2(new Vertice(pontos.get(i - 1)));
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    b = new Aresta();
                    b.setV1(new Vertice(pontos.get(i - 1)));
                    b.setV2(new Vertice(pontos.get(i - 1)));
                    b.getV2().setZ(z);
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    b = new Aresta();
                    b.setV1(new Vertice(pontos.get(i - 1)));
                    b.getV1().setZ(z);
                    b.setV2(new Vertice(pontos.get(i)));
                    b.getV2().setZ(z);
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    b = new Aresta();
                    b.setV1(new Vertice(pontos.get(i)));
                    b.setV2(new Vertice(pontos.get(i)));
                    b.getV1().setZ(z);
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    o.addFace(f3);
                    System.out.println("Criar Objeto - ADD Face");
                    
                //
                
                if (!f1.addAresta(a)) {
                    JOptionPane.showMessageDialog(rootPane, "Erro!");
                    break;
                }
            }
            
            Aresta a = new Aresta();
            a.setV1(new Vertice(pontos.get(pontos.size() - 1)));
            a.setV2(new Vertice(pontos.get(0)));
            if (!f1.addAresta(a)) {
                JOptionPane.showMessageDialog(rootPane, "Erro!");
            }
            System.out.println("Criar Objeto - ADD Aresta");
            //face lateral
                    Face f3= new Face();
                    Aresta b = new Aresta();
                    b.setV1(new Vertice(pontos.get(0)));
                    b.setV2(new Vertice(pontos.get(pontos.size() - 1)));
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    b = new Aresta();
                    b.setV1(new Vertice(pontos.get(pontos.size() - 1)));
                    b.setV2(new Vertice(pontos.get(pontos.size() - 1)));
                    b.getV2().setZ(z);
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    b = new Aresta();
                    b.setV1(new Vertice(pontos.get(pontos.size() - 1)));
                    b.getV1().setZ(z);
                    b.setV2(new Vertice(pontos.get(0)));
                    b.getV2().setZ(z);
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    b = new Aresta();
                    b.setV1(new Vertice(pontos.get(0)));
                    b.getV1().setZ(z);
                    b.setV2(new Vertice(pontos.get(0)));
                    f3.addAresta(b);
                    System.out.println("Criar Objeto - ADD Aresta");
                    
                    o.addFace(f3);
                    System.out.println("Criar Objeto - ADD Face");
                    
                //

            //cria a face de baixo do objeto
            for (int i = pontos.size() - 1; i > 0; i--) {
                a = new Aresta();
                a.setV1(new Vertice(pontos.get(i)));
                a.setV2(new Vertice(pontos.get(i - 1)));
                a.getV1().setZ(z);
                a.getV2().setZ(z);
                if (!f2.addAresta(a)) {
                    JOptionPane.showMessageDialog(rootPane, "Erro!");
                    break;
                }
                System.out.println("Criar Objeto - ADD Aresta");
            }
            a = new Aresta();
            a.setV1(new Vertice(pontos.get(0)));
            a.setV2(new Vertice(pontos.get(pontos.size() - 1)));
            a.getV1().setZ(z);
            a.getV2().setZ(z);
            if (!f2.addAresta(a)) {
                JOptionPane.showMessageDialog(rootPane, "Erro!");
            }
            System.out.println("Criar Objeto - ADD Aresta");
            if(!o.addFace(f1)) {
                JOptionPane.showMessageDialog(rootPane, "Erro!");
            }
            System.out.println("Criar Objeto - ADD Face");
            if(!o.addFace(f2)) {
                JOptionPane.showMessageDialog(rootPane, "Erro!");
            }
            System.out.println("Criar Objeto - ADD Face");
            
            try{
                ControlaTudo.addObj(o);
                JOptionPane.showMessageDialog(rootPane, "Objeto criado!");
                dispose();
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Erro!");
            }
            
            
            

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CriarObjeto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
